FROM eclipse-temurin:21-jre

WORKDIR /app

COPY worker/build/libs/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY worker/build/libs/*.jar /app/app.jar

EXPOSE 9000

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
